version: '2.0'
services:
  postgres:
    container_name: postgres-history-puzzle
    image: postgres
    environment:
      POSTGRES_DB: history_puzzle
      POSTGRES_USER: local_user
      POSTGRES_PASSWORD: local_password
      PGDATA: /data/postgres
    #    volumes:
    #      - postgres:/data/postgres
    ports:
      - 5432:5432